/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnlineConsultationRouteImport } from './routes/online-consultation'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppFamilyRouteImport } from './routes/app.family'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPrescriptionsRouteImport } from './routes/app.prescriptions'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppSavedRouteImport } from './routes/app.saved'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'
import { Route as ClinicsIndexRouteImport } from './routes/clinics.index'
import { Route as ClinicsClinicIdRouteImport } from './routes/clinics.$clinicId'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors.$doctorId'
import { Route as AppConsultAppointmentIdRouteImport } from './routes/app.consult.$appointmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineConsultationRoute = OnlineConsultationRouteImport.update({
  id: '/online-consultation',
  path: '/online-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsClinicIdRoute = ClinicsClinicIdRouteImport.update({
  id: '/clinics/$clinicId',
  path: '/clinics/$clinicId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConsultAppointmentIdRoute = AppConsultAppointmentIdRouteImport.update({
  id: '/consult/$appointmentId',
  path: '/consult/$appointmentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/offers': typeof OffersRoute
  '/online-consultation': typeof OnlineConsultationRoute
  '/specialties': typeof SpecialtiesRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/family': typeof AppFamilyRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/saved': typeof AppSavedRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/app/consult/$appointmentId': typeof AppConsultAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/offers': typeof OffersRoute
  '/online-consultation': typeof OnlineConsultationRoute
  '/specialties': typeof SpecialtiesRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/family': typeof AppFamilyRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/saved': typeof AppSavedRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/clinics': typeof ClinicsIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/app/consult/$appointmentId': typeof AppConsultAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/offers': typeof OffersRoute
  '/online-consultation': typeof OnlineConsultationRoute
  '/specialties': typeof SpecialtiesRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/family': typeof AppFamilyRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/saved': typeof AppSavedRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/app/consult/$appointmentId': typeof AppConsultAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/doctor'
    | '/offers'
    | '/online-consultation'
    | '/specialties'
    | '/app/appointments'
    | '/app/family'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/prescriptions'
    | '/app/records'
    | '/app/saved'
    | '/articles/$articleId'
    | '/book/$doctorId'
    | '/clinics/$clinicId'
    | '/doctors/$doctorId'
    | '/admin/'
    | '/app/'
    | '/articles/'
    | '/clinics/'
    | '/doctor/'
    | '/doctors/'
    | '/app/consult/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/offers'
    | '/online-consultation'
    | '/specialties'
    | '/app/appointments'
    | '/app/family'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/prescriptions'
    | '/app/records'
    | '/app/saved'
    | '/articles/$articleId'
    | '/book/$doctorId'
    | '/clinics/$clinicId'
    | '/doctors/$doctorId'
    | '/admin'
    | '/app'
    | '/articles'
    | '/clinics'
    | '/doctor'
    | '/doctors'
    | '/app/consult/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/doctor'
    | '/offers'
    | '/online-consultation'
    | '/specialties'
    | '/app/appointments'
    | '/app/family'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/prescriptions'
    | '/app/records'
    | '/app/saved'
    | '/articles/$articleId'
    | '/book/$doctorId'
    | '/clinics/$clinicId'
    | '/doctors/$doctorId'
    | '/admin/'
    | '/app/'
    | '/articles/'
    | '/clinics/'
    | '/doctor/'
    | '/doctors/'
    | '/app/consult/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  OffersRoute: typeof OffersRoute
  OnlineConsultationRoute: typeof OnlineConsultationRoute
  SpecialtiesRoute: typeof SpecialtiesRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  ClinicsClinicIdRoute: typeof ClinicsClinicIdRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-consultation': {
      id: '/online-consultation'
      path: '/online-consultation'
      fullPath: '/online-consultation'
      preLoaderRoute: typeof OnlineConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions': {
      id: '/app/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saved': {
      id: '/app/saved'
      path: '/saved'
      fullPath: '/app/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$clinicId': {
      id: '/clinics/$clinicId'
      path: '/clinics/$clinicId'
      fullPath: '/clinics/$clinicId'
      preLoaderRoute: typeof ClinicsClinicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId': {
      id: '/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/consult/$appointmentId': {
      id: '/app/consult/$appointmentId'
      path: '/consult/$appointmentId'
      fullPath: '/app/consult/$appointmentId'
      preLoaderRoute: typeof AppConsultAppointmentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppFamilyRoute: typeof AppFamilyRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConsultAppointmentIdRoute: typeof AppConsultAppointmentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppFamilyRoute: AppFamilyRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSavedRoute: AppSavedRoute,
  AppIndexRoute: AppIndexRoute,
  AppConsultAppointmentIdRoute: AppConsultAppointmentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DoctorRouteChildren {
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRouteWithChildren,
  OffersRoute: OffersRoute,
  OnlineConsultationRoute: OnlineConsultationRoute,
  SpecialtiesRoute: SpecialtiesRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  ClinicsClinicIdRoute: ClinicsClinicIdRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
